In [ ]:
#Array Creation and Basic Operations:
import numpy as np
array1=np.arange(1,21)
type(array1)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [8]:
add_array1=array1 +5
sum_array=np.sum(array1)
print(sum_array)


210


In [10]:
sub_array1=array1 -5
mean_array1=np.mean(array1)
print(mean_array1)

10.5


In [11]:
mul_array1=array1 *5
max_array1=np.max(array1)
print(max_array1)

20


In [13]:
div_array1=array1 /5
min_array1=np.min(array1)
print(min_array1)

1


In [15]:
#Array Indexing and Slicing:
import numpy as np
array1=np.random.randint(10,51,size=(4,5))
print(array1)


[[35 33 44 21 43]
 [41 25 39 31 45]
 [28 47 50 20 11]
 [50 27 48 24 17]]


In [19]:
extract_column=array1[:,2]
print(extract_column)

[44 39 50 48]


In [27]:
extract_rows=array1[:2]
print(extract_rows)

[[35 33 44 21 43]
 [41 25 39 31 45]]


In [ ]:
=[random_array>25]=100
print(array1)

SyntaxError: cannot assign to comparison (769700628.py, line 1)

In [33]:
#Array Reshaping:
array1=np.arange(1,13).reshape(3,4)
print(array1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
# BR0ADCASTING
array1=([[1],[2],[4],[5]])
array2=([1,2,3,4])
result=array1+array2
print(result)

[[1], [2], [4], [5], 1, 2, 3, 4]


In [3]:
import numpy as np
array=np.random.rand(3,3)
array
mean=np.mean(array)
std=np.std(array)
var=np.var(array)
print('mean:',mean)
print('standard deviation:',std)
print('variance:',var)
median0=np.median(array,axis=0)
median1=np.median(array,axis=1)
print('median along axis 0:',median0)
print('median along axis 1:',median1)



mean: 0.46410286163034303
standard deviation: 0.21901909774991526
variance: 0.047969365179186936
median along axis 0: [0.6666075  0.38164589 0.48082918]
median along axis 1: [0.48082918 0.72145302 0.43226133]


In [10]:
import  numpy as np 
array=np.random.randint(50,100,15)
print(array)
sorted=np.sort(array)
print('sorted:',sorted)
indices=np.where(array>75)
print('indices greater than 75:',indices)

[62 50 74 74 83 58 57 83 99 68 75 72 64 79 99]
sorted: [50 57 58 62 64 68 72 74 74 75 79 83 83 99 99]
indices greater than 75: (array([ 4,  7,  8, 13, 14]),)


In [12]:
import numpy as np
arr1 = np.random.randint(1, 10, (3, 3))
arr2 = np.random.randint(1, 10, (3, 3))
add=arr1+arr2
sub=arr1-arr2
mult=arr1*arr2
div=arr1/arr2
dot_product=np.dot(arr1,arr2)
print(arr1)
print(arr2)
print('addition:',add)
print('subtraction:',sub)
print('multiplication:',mult)
print('division:',div)
print('dot product:',dot_product)



[[6 9 9]
 [8 6 9]
 [2 2 5]]
[[5 3 1]
 [5 5 1]
 [3 8 2]]
addition: [[11 12 10]
 [13 11 10]
 [ 5 10  7]]
subtraction: [[ 1  6  8]
 [ 3  1  8]
 [-1 -6  3]]
multiplication: [[30 27  9]
 [40 30  9]
 [ 6 16 10]]
division: [[1.2        3.         9.        ]
 [1.6        1.2        9.        ]
 [0.66666667 0.25       2.5       ]]
dot product: [[102 135  33]
 [ 97 126  32]
 [ 35  56  14]]


In [2]:
pip install opencv-python

   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB 1.4 MB/s eta 0:00:29
   ---------------------------------------- 0.1/38.8 MB 1.4 MB/s eta 0:00:27
   ---------------------------------------- 0.3/38.8 MB 2.3 MB/s eta 0:00:17
    --------------------------------------- 0.6/38.8 MB 3.6 MB/s eta 0:00:11
   - -------------------------------------- 1.0/38.8 MB 4.7 MB/s eta 0:00:09
   - -------------------------------------- 1.5/38.8 MB 5.6 MB/s eta 0:00:07
   -- ------------------------------------- 2.0/38.8 MB 6.3 MB/s eta 0:00:06
   -- ------------------------------------- 2.4/38.8 MB 7.3 MB/s eta 0:00:06
   --- ------------------------------------ 3.1/38.8 MB 7.9 MB/s eta 0:00:05
   --- ------------------------------------ 3.7/38.8 MB 8.3 MB/s eta 0:00:05
   ---- ----------------------------------- 4.2/38.8 MB 8.7 MB/s eta 0:00:04
   ---- ----------------------------------- 4.8/38.8 MB 9.1 MB/s eta 0:00:04
   ---


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: C:\Users\adhar\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [1]:

import numpy as np
import cv2
white_image=np.full((400,400,3),225,dtype=np.uint8)
cv2.imshow('White Image',white_image)
#cv2.waitKey(0)
cv2.destroyAllWindows()


In [5]:

import numpy as np
import cv2
white_image=np.zeros((400,400,3),dtype=np.uint8)
white_image[:,:]=[100,99,9]
cv2.imshow('White Image',white_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
