In [8]:
import numpy as np
array1=np.array([1,2,3])
type(array1)
array1.shape

(3,)

In [9]:
import numpy as np
array1=np.array([1,2,3])
type(array1)
array1.ndim

1

In [10]:
import numpy as np
array2=np.array([[1,2,3],
                [4,5,6]])
array2.shape

(2, 3)

In [15]:
import numpy as np
array2=np.array([[1,2,3],
                [4,5,6]])
type(array1)
array1.size

3

In [12]:
import numpy as np
array2=np.array([[1,2,3],
                [4,5,6]])
array2.dtype

dtype('int64')

In [14]:
import numpy as np
array2=np.array([[1,2,3],
                [4,5,6]],dtype='float')
array2.dtype

dtype('float64')

In [16]:
np.array((1,2,3))

array([1, 2, 3])

In [17]:
zero=np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
full=np.full((2,3),6,dtype='complex')
print(full)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [ ]:
e=np.random.random

In [33]:
f=np.arange(2,10000,5)
f

array([   2,    7,   12, ..., 9987, 9992, 9997])

In [35]:
g=np.linspace(1,5,40)
g

array([1.        , 1.1025641 , 1.20512821, 1.30769231, 1.41025641,
       1.51282051, 1.61538462, 1.71794872, 1.82051282, 1.92307692,
       2.02564103, 2.12820513, 2.23076923, 2.33333333, 2.43589744,
       2.53846154, 2.64102564, 2.74358974, 2.84615385, 2.94871795,
       3.05128205, 3.15384615, 3.25641026, 3.35897436, 3.46153846,
       3.56410256, 3.66666667, 3.76923077, 3.87179487, 3.97435897,
       4.07692308, 4.17948718, 4.28205128, 4.38461538, 4.48717949,
       4.58974359, 4.69230769, 4.79487179, 4.8974359 , 5.        ])

In [11]:
array=np.array([[1,2,3,4],
                [5,6,7,8],
                [2,3,4,9]])
new_array=array.reshape(4,3)
print(new_array)

[[1 2 3]
 [4 5 6]
 [7 8 2]
 [3 4 9]]


In [12]:
new_array=array.reshape(6,2)
print(new_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [2 3]
 [4 9]]


In [13]:
new_array=array.reshape(2,2,3)
print(new_array)

[[[1 2 3]
  [4 5 6]]

 [[7 8 2]
  [3 4 9]]]


In [15]:
new_array=array2.flatten()
new_array

NameError: name 'array2' is not defined

In [16]:
import numpy as np
arr=np.array([[1,2,3,4],
      [2,3,4,5]])
new_array=arr.reshape(2,2,2)
print(new_array)

[[[1 2]
  [3 4]]

 [[2 3]
  [4 5]]]


In [22]:
arr=np.array([2,3,4,5,6,7,8,9])
shape=arr.reshape(-1,4)
print(shape)

[[2 3 4 5]
 [6 7 8 9]]


In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape=arr.reshape(6)
display(shape)

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape=arr.reshape(6)
display(shape)

In [31]:
np.sum(arr)

np.int64(21)

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape=arr.reshape(3,1,2)
display(shape)

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2=np.array([[2,3,4]])
concat_array=np.concatenate((arr,arr2))
print(concat_array)  

[[1 2 3]
 [4 5 6]
 [2 3 4]]


In [6]:
import numpy as np
arr1=np.array([[1,2,3,4,5],[6,7,7,8,8]])
new_array=np.vsplit(arr1,2)
print(new_array)


[array([[1, 2, 3, 4, 5]]), array([[6, 7, 7, 8, 8]])]


In [14]:
import numpy as np
arr1=np.array([[1,2,3,4,5,7],[6,7,7,8,8,9]])
new_array=np.hsplit(arr1,2)
print(new_array)


[array([[1, 2, 3],
       [6, 7, 7]]), array([[4, 5, 7],
       [8, 8, 9]])]


In [16]:
import numpy as np
arr1=np.array([1,2,3,5])
arr2=np.array([[1],[2],[4]])
arr1+arr2



array([[2, 3, 4, 6],
       [3, 4, 5, 7],
       [5, 6, 7, 9]])

In [22]:
import numpy as np
arr1=np.array([[1,2,3],[1,2,5],[8,9,7]])
arr2=np.array([[1],[2],[4]])
arr1+arr2



array([[ 2,  3,  4],
       [ 3,  4,  7],
       [12, 13, 11]])

In [23]:
pip install cv2


Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: C:\Users\adhar\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
